name: Docker Image Security Scan

on:
  workflow_dispatch:
    inputs:
      image_name:
        description: "Nome da imagem p√∫blica do Docker Hub (ex: alpine, nginx, ubuntu)"
        required: true
        default: "alpine"

jobs:
  scan-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Pull Docker image
        run: docker pull ${{ github.event.inputs.image_name }}

      - name: List Docker image
        run: docker images | grep ${{ github.event.inputs.image_name }}

      - name: Scan vulnerabilities with Docker Scout
        uses: docker/scout-action@v1
        with:
          image: ${{ github.event.inputs.image_name }}
