name: Vendo arquivos compartilhados entre Steps e Jobs

on:
  workflow_dispatch:
    
jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - name: Confere Versao do ubuntu
        run: cat /etc/os-release
      
      - name: Exibir Uma Mensagem
        run: echo "Estou faazendo o curso de GitHub Actions da LinuxTisp" > ${{ github.workspace }}/mensagem.txt

      - uses: actions/upload-artifact@v4
        with:
          name: strigus-upload
          path: ${{ github.workspace}}/mensagem.txt

  job_2:
    runs-on: ubuntu-latest
    steps:
      - name: Ver o conteudo do diretorio
        run: ls -lha

      - uses: actions/download-artifact@v4
        with:
          name: strigus-upload
          path: strigus
      
      - name: Ver o conteudo do diretorio
        run: ls -lha && ls ./strigus/

      - name: Direciona o arquivo
        run: mv strigus/mensagem.txt . && rm -rf ./strigus

      - name: ver o conteudo do diretorio
        run: ls -lha  

      - name: Le Conte√∫do
        run: cat mensagem.txt